#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the navbar)
name: "Tony Neufeld's Blog"

# Your site's title (e.g., Ben's Awesome Site, The GitHub Blog, etc.), used as part of the title tag like Home | Ben's Awesome Site.
title: "Tony Neufeld: Personal Finance, Lifestyle Design, and Becoming a Dad in Saskatchewan"


# Link to avatar in the navbar (/assets/images/avatar.png). Leave empty if no logo desired. Two avatars for light and dark mode.
# Avatar for light mode site
lightavatar: coffeecup.png
# Avatar for dark mode site
darkavatar: coffeecup_white.PNG

# A short description (e.g., A blog dedicated to reviewing cat gifs), used as part of the title tag like Ben's Awesome Site | A blog dedicated to reviewing cat gifs instead of Ben's Awesome Site | Long description about a blog dedicated to reviewing cat gifs that would be used when page.title is not defined.
tagline: "Helping young professionals, immigrants, indigenous folks, new parents, and families simplify their finances, build wealth, and align their money with the life they want to live — all with a distinctly Saskatchewan lens."

# A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
description: "Practical insights on lifestyle design and personal finance in Saskatchewan — helping young professionals, immigrants, indigenous folks, new parents, and families simplify their finances, build wealth, and align their money with the life they want to live — all with a distinctly Saskatchewan lens."

# The full URL to your site. Note: site.github.url will be used by default.
url: tonyneufeld.blog

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# global author information
author: tony-neufeld

# URL to a site-wide logo (e.g., /assets/your-company-logo.png)
logo: coffeecup.png

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-FM601HF0DV

permalink: /:year/:month/:day/:title/

# Includes an icon in the footer for each username you enter
footer-links:
  email: tonyjneufeld@gmail.com
  facebook:
  github:
  instagram: 
  linkedin: 
  rss: test_rss_tonyneufeld_blog
  twitter: 
  strava: 137288884

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
